### ISSUE TITLE
Update REAME.md

### ISSUE THREAD

**Issue by jeyemwey** [jofftiquez/scope-of-works#10]
Update the readme. 

1. Add a directory of available math functions
2. Maybe a table with `name`, `params` and `description` will suffice.

| name | params | description | 
| ----- | ------- | ----------- |
| `areaTrapezoid ` | `a`, `b`, `height` | Returns the area of a trapezoid. |

**Comment by computamike** [comment]
I can have a go at this when I get back home (roughly 1.5 hours) - would that be ok?

**Comment by jofftiquez** [comment]
@computamike certainly! Thanks.

**Comment by jofftiquez** [comment]
@computamike kindly re-fork. I updated some stuff. Thanks

**Comment by computamike** [comment]
no problem - so to confirm I'll be updating https://github.com/jofftiquez/scope-of-works/blob/master/README.md with examples that match the actual operations - is that what you're expecting?

**Comment by jeyemwey** [comment]
@computamike Hi, since @jofftiquez is probably sleeping right now, I can only share my expectations: The given example in the Readme is outdated, so we'll need to update it.

I guess, one example should do the job :)

**Comment by jofftiquez** [comment]
@computamike  good day. @jeyemwey is right, one example should be enough. I updated the description of this issue. Thanks!

**Comment by jeyemwey** [comment]
Since #16 is merged, I'll close this issue.
